### ISSUE TITLE
Does not preserve layout when closing diff view

### ISSUE THREAD

**Issue by Kyle-Shanks** [predragnikolic/sublime-git-diff-view#12]
If you are using a layout that is not one column, opening and then closing the diff view will revert back to one column view instead of the layout used before.

Looks like it is reverted here: https://github.com/predragnikolic/sublime-git-diff-view/blob/40d6924e50900cbf34dcdb8772b40ca5b3f1f1f8/GitDiffView.py#L84

**Comment by predragnikolic** [comment]
Yes the current behavior can be improved by restoring the layout to the last saved window.get_layout().

**Comment by predragnikolic** [comment]
The fix is included in the [0.6.0 release](https://github.com/predragnikolic/sublime-git-diff-view/releases/tag/0.6.0)
