### ISSUE TITLE
Status view scrolls to bottom when adding/resetting file

### ISSUE THREAD

**Issue by lumnn** [predragnikolic/sublime-git-diff-view#3]
Hi. First of all - great plugin. Even that Sublime doesn't have sophisticated interface API as other ram hungry editors you've still managed to provide great functionality with easy to use UI.

The issue is about adding/reseting file from a status view using `a` key. When list of files exceeds the height of window then every time `a` key is pressed the view jumps to bottom. Caret stays in the same place.

OS: Arch Linux
Sublime Text 3180

**Comment by predragnikolic** [comment]
Thank you! I am really glad you find it intuitive :)
I will do a minor release for the fix soon.

**Comment by lumnn** [comment]
It's me again. I believe the issue is still there

**Comment by predragnikolic** [comment]
How can I reproduce that? Can you make a gif? :)

**Comment by predragnikolic** [comment]
I promise this time that it has been fixed with fb6d12f8f5fd497e5ef928b8118ef5ad911308da :)
