### ISSUE TITLE
Add an option to refresh

### ISSUE THREAD

**Issue by lumnn** [predragnikolic/sublime-git-diff-view#4]
Currently my workflow is:  
I stage few files, and commit through terminal  
Sometimes I repeat that until I commit all changed files, but that forces me to close and open diff view, every time I commit.

Would it be possible to add a automatic refresh feature, or at least add another shortcut (`r` feels the best) to refresh the view

**Comment by predragnikolic** [comment]
It would be great if I could find a way to listen to commit events, whether they came from the terminal or another app. 

I had this idea before, but I didn't find a way to do it. 

One way would be to update the list every second?

**Comment by predragnikolic** [comment]
I would go with the automatic refresh feature. 

I will probably set up a listener when the diff view opens to refresh the list every 1 or 2 seconds. 
So there wouldn't be a need for a refresh shortcut, the plugin will do it for you.

I will keep you notified about this, I am a bit busy with other thing right now :)

**Comment by predragnikolic** [comment]
I have some great news :)

![output](https://user-images.githubusercontent.com/22029477/53237438-fd0d1c80-3696-11e9-9053-062fa2c151cf.gif)

BTW, as you can see, #3 is fixed as well

The git status in sublime updates when you stage/unstage/commit through the terminal, command palette, or anywhere. :smile: 

But, I wont make a release until I use it for a while to see if there are any problems with it.
You can try it by following the installation steps for the dev version https://github.com/predragnikolic/sublime-git-diff-view#development-version

**Comment by lumnn** [comment]
That looks great! Great work!
