### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by mustafa0x** [predragnikolic/sublime-git-diff-view#5]
Hi, I installed this package with many windows open, and it froze my computer.

See the CPU usage %:

![cpu](https://user-images.githubusercontent.com/1473102/52521133-78c49d80-2c83-11e9-86cf-b9404cff7e15.png)

**Comment by predragnikolic** [comment]
You are on Mac OS, right?

Can you tell me the exact steps to take to replicate this?

**Comment by predragnikolic** [comment]
Also, what is you version of Sublime?
If you deactivate this plug-in, does the CPU goes down?

**Comment by mustafa0x** [comment]
This happened after I installed the plugin. I didn't do anything else.

v3.1.1 Build 3176

I'd just check to make sure you don't do anything CPU intensive (e.g. indexing) on plugin install or in the background in general.

**Comment by predragnikolic** [comment]
I don't do any indexing :-D I don't know what could cause this,

I will investigate this :-)

Do you have high CPU usage after you installed the plug-in?
