### ISSUE TITLE
Cannot navigate through files on version 0.4.4

### ISSUE THREAD

**Issue by federf** [predragnikolic/sublime-git-diff-view#8]
I can no longer navigate through my modified files on the diff view on the last version (0.4.4)

It was working fine on previous version (0.4.3).

I've just manually installed version 0.4.3 and it works fine again.

I have sublime V. 3

**Comment by predragnikolic** [comment]
Hello,
I can't seem to reproduce it.

![output](https://user-images.githubusercontent.com/22029477/78939454-7abb0400-7ab4-11ea-8ae4-efb80503881b.gif)

On what os are you?
Can you maybe just reinstall it and see if it fixes the problem :)

**Comment by predragnikolic** [comment]
You can open the git diff view, and use your up and down arrows. 
If the error happens,
open up the sublime console ctrl+` .
There will probably be and error message, 
just copy and paste the error here.

**Comment by federf** [comment]
Hi, I'm on macOs Mojave 10.14.6.

I have tried reinstalling the package again and now the error is not happening.

Yesterday I tried reinstalling the package but I was having the error anyways.
That's why I've tried installing previous version (0.4.3) and in that version I did not have any issue.

Anyways, you can close this issue.

Thanks for your time.

**Comment by predragnikolic** [comment]
If you experience the same but again reopen the issue, but make sure to copy the error from the Sublime console 🙂
