### ISSUE TITLE
key binding doesn't work -> other available options?

### ISSUE THREAD

**Issue by ldm1417** [predragnikolic/sublime-git-diff-view#9]
Hello,

I installed your package on the latest Sublime Linux.

1) How should I "tie" the package to the repository? Will it get "tied" automatically? Once I open a file the package will recognize its repository?
2) The default keybinding doesn't  work ... Tried to change it to another one - still dosn't work... Is there a way to open the Git Status and GitDiffView windows by another way?
3) in the package description you stated that "git view won't open if there are no git changes". But if there are local changes in the file, how can I see the differences between a file in the local directory and the same file in the remote directory? 

Thank you!

**Comment by predragnikolic** [comment]
Hello :)

1. This plugin works only in git initialized repositories. You don't need to do anything. 

2. "The default keybinding doesn't work ", strange. On what OS are you? 
The default keybinding for Linux and Windows is, `ctrl+shift+g`, for mac is `alt+shift+g`.
You can try overriding the default keybinding to something different. 
```
[             // override this
    { "keys": ["ctrl+shift+g"], "command": "toggle_git_diff_view"}
]
```

3. To answer your question, let me explain how this plugin works. 
This plugin will run the `git status` command and will just output the result. If `git status` outputs that there a no git changes, there is no point in showing the diff view, so I just show a message that "there are no git changes".

My question to you is can you open the GitDiffView at all?

**Comment by ldm1417** [comment]
The OS is CentOS7 (linux). 
I tried to remap the keybinding - doesn't help. 
You wrote: "My question to you is can you open the GitDiffView at all?". So, how can I do so without keybinding? I installed the package, see it under Package Settings, but how can I open it without a key binding? 
BTW, Sublime recognizes the git repository - there is a 'master' sign in the button right corner...

**Comment by nerdCopter** [comment]
i dont know that it's working on mine either `Ctrl-shift-G` Debain 11.

but no other indicators.
changing to `"staged_symbol": "M",` does nothing for me.
i do not know what to expect by ctrl-shift-g, nothing else opens nor displays.

i only see this: (which is still difficult to locate mods)
![image](https://user-images.githubusercontent.com/56646290/201963054-8079ed70-7e18-47ae-b6cb-2b103982811e.png)


i feel like a minimap-highlight would be ultra useful.

**Comment by predragnikolic** [comment]
you can open the git diff view via the command palette, `Git Diff View: Toggle`.
![Screenshot from 2023-06-10 00-18-37](https://github.com/predragnikolic/sublime-git-diff-view/assets/22029477/88fd668c-356b-4c24-82fa-fa6326cb511c)

Or assign a keybinding 
```
[
    { "keys": ["ctrl+shift+g"], "command": "toggle_git_diff_view"}
]
```

Because of that, I will close the ticket.
